 services:
  db:
    image: postgres:20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: julietasanchez25
      POSTGRES_PASSWORD: Julieta25
      POSTGRES_DB: admin_25
      volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    depends_on:
      - POSTGRES_DB
    ports: 
      - 8080:8080

volumes:
 postgres_data:
